### ISSUE TITLE
When starting in localhost mode, mongo error

### ISSUE THREAD

**Issue by lenkrasinski** [MadlabsInc/mevn-cli#187]
starting in localhost mode
When I start the server using npm run dev I get the following error, **I must be missing something**

Listening On http://localhost:9000/api
Mongo CONNECT error: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (/Users/leonardrkrasinski/Documents/Docker/mevn/todo/server/node_modules/mongoose/lib/connection.js:800:32)
    at /Users/leonardrkrasinski/Documents/Docker/mevn/todo/server/node_modules/mongoose/lib/index.js:341:10
    at /Users/leonardrkrasinski/Documents/Docker/mevn/todo/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/Users/leonardrkrasinski/Documents/Docker/mevn/todo/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Mongoose.connect (/Users/leonardrkrasinski/Documents/Docker/mevn/todo/server/node_modules/mongoose/lib/index.js:340:10)
    at init (/Users/leonardrkrasinski/Documents/Docker/mevn/todo/server/helpers/db/mongodb.js:7:6)
    at Object.<anonymous> (/Users/leonardrkrasinski/Documents/Docker/mevn/todo/server/server.js:8:35)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by jamesgeorge007** [comment]
Please make sure that the MongoDB service is up and running.

**Comment by jamesgeorge007** [comment]
Closing, feel free to continue the discussion here.
